# Generated by Django 5.1.3 on 2024-12-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Reply',
        ),
    ]
